### ISSUE TITLE
Do we need Stone resource Tiles?

### ISSUE THREAD

**Issue by RobertJNicholds** [Wolfie13/RTSAI#5]
Should we have stone as a resource, or just make it so quarries can be built anywhere?
PDDL is set up at the moment so they can be built anywhere, but I can change this really quickly

**Comment by maxaction** [comment]
I think leaving it as it is should be fine. It doesn't say in the spec that it should be on a resource.

**Comment by RobertJNicholds** [comment]
That's what I thought also, so will keep it the same
